### ISSUE TITLE
Randomizing the board can produce unsolvable puzzles

### ISSUE THREAD

**Issue by MichaelRijsdijk** [cnnranderson/Slidez#1]
The code for randomizing the tiles can produce unsolvable puzzles:

nums.shuffle();
// Randomize hole location
holeX = MathUtils.random(0, boardSize - 1);
holeY = MathUtils.random(0, boardSize - 1);

There is some math explanations on whether or not a puzzle is solvable:
https://www.cs.bham.ac.uk/~mdr/teaching/modules04/java2/TilesSolvability.html

There are a couple of solutions:
- Implement a method to check solvability based on math.
- Implement a method to utilize the moveButtons method to do a number of valid moves to shuffle the tiles.

**Comment by cnnranderson** [comment]
This is correct. I had loosely thrown together the "randomization" aspect, without much respect for a correct and "solvable" puzzle. I carelessly approached this just to get the players into the idea of variability in their game. I will modify this in the next few days. Thank you for the clean write up!

**Comment by MichaelRijsdijk** [comment]
No problem. Thanks for the youtube series, I've enjoyed it quite a bit!
